# Generated by Django 5.0.1 on 2024-02-27 01:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import django_countries.fields
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='First Name of the user', max_length=150)),
                ('last_name', models.CharField(help_text='Last Name of the user', max_length=150)),
                ('phone_number', models.CharField(help_text='Phone Number of the user, (Eg: +1 (123) 456-7890)', max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +1 (513) 123-7890', regex='^\\+1 \\(\\d{3}\\) \\d{3}-\\d{4}$')])),
                ('current_address', models.CharField(help_text='Current Address of the user', max_length=500)),
                ('city', models.CharField(help_text='Enter Current City', max_length=25)),
                ('state', localflavor.us.models.USStateField(help_text='Please select your state', max_length=2)),
                ('country', django_countries.fields.CountryField(help_text='Please select your country', max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(help_text='Please enter your ZIP code in the format XXXXX or XXXXX-XXXX.', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid ZIP code in the format XXXXX or XXXXX-XXXX.', regex='^\\d{5}(?:-\\d{4})?$')])),
                ('is_admin', models.BooleanField(default=False, help_text='Admin User')),
                ('is_tenant', models.BooleanField(default=False, help_text='Customer/Tenant User')),
                ('is_active', models.BooleanField(default=True, help_text='Active or Inactive User')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
